face/urls.py
from django.urls import path
from . import views

app_name = 'face'

urlpatterns = [
    path('', views.addUser, name='home'),
]

face_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('face.urls', namespace='core'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

face/models.py
from django.db import models

def upload_to(instance, filename):
    return '{name}/{filename}'.format(name=instance.user.name, filename=filename)


class User(models.Model):
    name = models.CharField(max_length=80, unique=True)

    def __str__(self):
        return self.name

class UserImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=upload_to)

    def __str__(self):
        return f"{self.user.name}'s image"

face/forms.py
from django import forms
from .models import User, UserImage


class UserForm(forms.ModelForm):
    name = forms.CharField(max_length=80)
    class Meta:
        model = User
        fields = ['name',]

class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')

    class Meta:
        model = UserImage
        fields = ['image']

class _UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name']


class UserFullForm(UserForm):
    images = forms.FileField(widget=forms.ClearableFileInput(
        attrs={'multiple': True}), required=False)

    class Meta(_UserForm.Meta):
        fields = _UserForm.Meta.fields + ['images']

face/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.forms import modelform_factory
from .models import User, UserImage
from .forms import UserForm, ImageForm, UserFullForm

# Create your views here.
def add_face(request):
    ImageFormSet = modelform_factory(UserImage, form=ImageForm, extra=5)
    if request.method == 'POST':
        pass
    else:
        userForm = UserForm()
        formset = ImageFormSet()
        context = {'userForm': userForm, 'formset': formset}
        return render(request, 'face/index.html', context)


def addUser(request):
    if request.method == "POST":
        form = UserFullForm(request.POST or None, request.FILES or None)
        files = request.FILES.getlist('images')
        print(files)
        if form.is_valid():
            name = form.cleaned_data['name']
            user = User.objects.create(name=name)
            for f in files:
                UserImage.objects.create(user=user, image=f)
            user.save()
            return render(request, 'face/success.html')

        else:
            print("Form invalid, see below error msg")
            print(form.errors)
            return render(request, 'face/error.html', {'error': form})

    else:
        form = UserFullForm()
        context = {'form': form}
        return render(request, 'face/index.html', context)

face/templates/face/error.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Error</title>
    <link href="{% static 'styles.css' %}" rel="stylesheet" />
  </head>

  <body>
    <div class="container">
      <div class="error">
        <p>Name already exists, choose another name.</p>
        <a href={% url 'face:home' %}>Back</a>
      </div>  
    </div>
  </body>
</html>

face/templates/face/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Face register</title>
    <link href="{% static 'styles.css' %}" rel="stylesheet" />
  </head>

  <body>
    <div class="container">
      <div class="form">
        <h1>Register</h1>
        <p>Add atleast 10 pictures for best results, no hats or caps</p>
        <form
          id="post_form"
          action="{% url 'face:home' %}"
          method="post"
          enctype="multipart/form-data"
        >
          {% csrf_token %}
          <div>
            <input
              name="name"
              type="text"
              id="user-name"
              placeholder="Enter your name"
              class="name"
            />
          </div>
          <div>
            <input
              type="file"
              name="images"
              class="images"
              id="user-image"
              multiple="multiple"
            />
          </div>
          <div>
            <button type="submit">Add</button>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

face/templates/face/success.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Success</title>
    <link href="{% static 'styles.css' %}" rel="stylesheet" />
  </head>

  <body>
    <div class="container">
      <div class="success">
        <p>Pictures added, try scanning your face in a few mins.</p>
        <a href={% url 'face:home' %}>Add another user</a>
      </div>
    </div>
  </body>
</html>